velodyne_transform_node:
    ros__parameters:
        calibration: 32db.yaml
        model: 32E
        min_range: 0.9
        max_range: 50.0
        view_direction: 0.0
        fixed_frame: ""
        target_frame: ""
        organize_cloud: true
